.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ORANGE 1 2010-02-21
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
orange \- data mining framework
.SH SYNOPSIS
.B orange
.RI [ " files to open ... " ]
.SH DESCRIPTION
Orange is a component-based data mining software. It includes a range
of data visualization, exploration, preprocessing and modeling
techniques. It can be used through a nice and intuitive user interface
or, for more advanced users, as a module for Python programming language.

.B orange
command is a shortcut for graphical user interface.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
.\" \fB#PACKAGE#\fP is a program that...
.SH OPTIONS
One or more files can be passed to command to be opened with graphical user interface.
.SH SEE ALSO
.BR python (1)
.SH AUTHOR
Orange is developed at Laboratory of Artificial Intelligence, Faculty of Computer and Information Science, University of Ljubljana, Slovenia.
.PP
This manual page was written by Mitar <mitar@tnode.com>,
for the Debian project (but may be used by others).
