# -*- coding: utf-8 -*-
#
# widgets documentation build configuration file, created by
# sphinx-quickstart on Fri Oct  8 15:09:05 2010.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os, sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from conf import *

TITLE = "%s v%s" % ("Orange Widgets", VERSION)

html_title = TITLE
epub_title = TITLE

latex_documents = [
    ('index', 'reference.tex', TITLE,
     AUTHOR, 'manual'),
    ]



# rst epilog with shortcuts for screen shoot numbers
rst_epilog = """
.. |1| image:: /../../sphinx-ext/themes/orange_theme/static/images/1.png
       :align: middle
       :alt: 1
          
.. |2| image:: /../../sphinx-ext/themes/orange_theme/static/images/2.png
       :align: middle
       :alt: 2

.. |3| image:: /../../sphinx-ext/themes/orange_theme/static/images/3.png
       :align: middle
       :alt: 3
       
.. |4| image:: /../../sphinx-ext/themes/orange_theme/static/images/4.png
       :align: middle
       :alt: 4
       
.. |5| image:: /../../sphinx-ext/themes/orange_theme/static/images/5.png
       :align: middle
       :alt: 5
       
.. |6| image:: /../../sphinx-ext/themes/orange_theme/static/images/6.png
       :align: middle
       :alt: 6
       
.. |7| image:: /../../sphinx-ext/themes/orange_theme/static/images/7.png
       :align: middle
       :alt: 7
       
.. |8| image:: /../../sphinx-ext/themes/orange_theme/static/images/8.png
       :align: middle
       :alt: 8
       
.. |9| image:: /../../sphinx-ext/themes/orange_theme/static/images/9.png
       :align: middle
       :alt: 9
       
.. |10| image:: /../../sphinx-ext/themes/orange_theme/static/images/10.png
       :align: middle
       :alt: 10
"""
