"""
.. automodule:: Orange.preprocess.outliers
"""

from orange import \
     DomainContinuizer, \
    VariableFilterMap, \
    ValueFilter, \
         ValueFilter_continuous, \
         ValueFilter_discrete, \
         ValueFilter_string, \
         ValueFilter_stringList, \
    ValueFilterList, \
    TransformValue, \
         Discrete2Continuous, \
         Discretizer, \
              BiModalDiscretizer, \
              EquiDistDiscretizer, \
              IntervalDiscretizer, \
              ThresholdDiscretizer, \
         MapIntValue, \
         NormalizeContinuous, \
         Ordinal2Continuous, \
         TransformValue_IsDefined, \
    TableAverager, \
    Preprocessor, \
         Preprocessor_addCensorWeight, \
         Preprocessor_addClassNoise, \
         Preprocessor_addClassWeight, \
         Preprocessor_addGaussianClassNoise, \
         Preprocessor_addGaussianNoise, \
         Preprocessor_addMissing, \
         Preprocessor_addMissingClasses, \
         Preprocessor_addNoise, \
         Preprocessor_discretize, \
         Preprocessor_drop, \
         Preprocessor_dropMissing, \
         Preprocessor_dropMissingClasses, \
         Preprocessor_filter, \
         Preprocessor_ignore, \
         Preprocessor_imputeByLearner, \
         Preprocessor_removeDuplicates, \
         Preprocessor_select, \
         Preprocessor_shuffle, \
         Preprocessor_take, \
         Preprocessor_takeMissing, \
         Preprocessor_takeMissingClasses, \
    Imputer, \
         Imputer_asValue, \
         Imputer_defaults, \
         Imputer_model, \
         Imputer_random, \
    ImputerConstructor, \
         ImputerConstructor_asValue, \
         ImputerConstructor_average, \
         ImputerConstructor_maximal, \
         ImputerConstructor_minimal, \
         ImputerConstructor_model, \
         ImputerConstructor_random, \
    FilterList, \
    Filter, \
         Filter_conjunction, \
         Filter_disjunction, \
         Filter_hasClassValue, \
         Filter_hasMeta, \
         Filter_hasSpecial, \
         Filter_isDefined, \
         Filter_random, \
         Filter_sameValue, \
         Filter_values, \
    Discretization, \
         BiModalDiscretization, \
         EntropyDiscretization, \
         EquiDistDiscretization, \
         EquiNDiscretization, \
    DomainTransformerConstructor, \
    RemoveRedundant, \
         RemoveRedundantByInduction, \
         RemoveRedundantByQuality, \
         RemoveRedundantOneValue, \
    RemoveUnusedValues

import outliers
