# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marko/orangehg/source/orangeqt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marko/orangehg/source/orangeqt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marko/orangehg/source/orangeqt/CMakeFiles /home/marko/orangehg/source/orangeqt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marko/orangehg/source/orangeqt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named python_module_orangeqt

# Build rule for target.
python_module_orangeqt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 python_module_orangeqt
.PHONY : python_module_orangeqt

# fast build rule for target.
python_module_orangeqt/fast:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/build
.PHONY : python_module_orangeqt/fast

canvas3d.o: canvas3d.cpp.o
.PHONY : canvas3d.o

# target to build an object file
canvas3d.cpp.o:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/canvas3d.cpp.o
.PHONY : canvas3d.cpp.o

canvas3d.i: canvas3d.cpp.i
.PHONY : canvas3d.i

# target to preprocess a source file
canvas3d.cpp.i:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/canvas3d.cpp.i
.PHONY : canvas3d.cpp.i

canvas3d.s: canvas3d.cpp.s
.PHONY : canvas3d.s

# target to generate assembly for a file
canvas3d.cpp.s:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/canvas3d.cpp.s
.PHONY : canvas3d.cpp.s

curve.o: curve.cpp.o
.PHONY : curve.o

# target to build an object file
curve.cpp.o:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/curve.cpp.o
.PHONY : curve.cpp.o

curve.i: curve.cpp.i
.PHONY : curve.i

# target to preprocess a source file
curve.cpp.i:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/curve.cpp.i
.PHONY : curve.cpp.i

curve.s: curve.cpp.s
.PHONY : curve.s

# target to generate assembly for a file
curve.cpp.s:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/curve.cpp.s
.PHONY : curve.cpp.s

glextensions.o: glextensions.cpp.o
.PHONY : glextensions.o

# target to build an object file
glextensions.cpp.o:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/glextensions.cpp.o
.PHONY : glextensions.cpp.o

glextensions.i: glextensions.cpp.i
.PHONY : glextensions.i

# target to preprocess a source file
glextensions.cpp.i:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/glextensions.cpp.i
.PHONY : glextensions.cpp.i

glextensions.s: glextensions.cpp.s
.PHONY : glextensions.s

# target to generate assembly for a file
glextensions.cpp.s:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/glextensions.cpp.s
.PHONY : glextensions.cpp.s

multicurve.o: multicurve.cpp.o
.PHONY : multicurve.o

# target to build an object file
multicurve.cpp.o:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/multicurve.cpp.o
.PHONY : multicurve.cpp.o

multicurve.i: multicurve.cpp.i
.PHONY : multicurve.i

# target to preprocess a source file
multicurve.cpp.i:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/multicurve.cpp.i
.PHONY : multicurve.cpp.i

multicurve.s: multicurve.cpp.s
.PHONY : multicurve.s

# target to generate assembly for a file
multicurve.cpp.s:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/multicurve.cpp.s
.PHONY : multicurve.cpp.s

networkcurve.o: networkcurve.cpp.o
.PHONY : networkcurve.o

# target to build an object file
networkcurve.cpp.o:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/networkcurve.cpp.o
.PHONY : networkcurve.cpp.o

networkcurve.i: networkcurve.cpp.i
.PHONY : networkcurve.i

# target to preprocess a source file
networkcurve.cpp.i:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/networkcurve.cpp.i
.PHONY : networkcurve.cpp.i

networkcurve.s: networkcurve.cpp.s
.PHONY : networkcurve.s

# target to generate assembly for a file
networkcurve.cpp.s:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/networkcurve.cpp.s
.PHONY : networkcurve.cpp.s

plot.o: plot.cpp.o
.PHONY : plot.o

# target to build an object file
plot.cpp.o:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/plot.cpp.o
.PHONY : plot.cpp.o

plot.i: plot.cpp.i
.PHONY : plot.i

# target to preprocess a source file
plot.cpp.i:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/plot.cpp.i
.PHONY : plot.cpp.i

plot.s: plot.cpp.s
.PHONY : plot.s

# target to generate assembly for a file
plot.cpp.s:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/plot.cpp.s
.PHONY : plot.cpp.s

plot3d.o: plot3d.cpp.o
.PHONY : plot3d.o

# target to build an object file
plot3d.cpp.o:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/plot3d.cpp.o
.PHONY : plot3d.cpp.o

plot3d.i: plot3d.cpp.i
.PHONY : plot3d.i

# target to preprocess a source file
plot3d.cpp.i:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/plot3d.cpp.i
.PHONY : plot3d.cpp.i

plot3d.s: plot3d.cpp.s
.PHONY : plot3d.s

# target to generate assembly for a file
plot3d.cpp.s:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/plot3d.cpp.s
.PHONY : plot3d.cpp.s

plotitem.o: plotitem.cpp.o
.PHONY : plotitem.o

# target to build an object file
plotitem.cpp.o:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/plotitem.cpp.o
.PHONY : plotitem.cpp.o

plotitem.i: plotitem.cpp.i
.PHONY : plotitem.i

# target to preprocess a source file
plotitem.cpp.i:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/plotitem.cpp.i
.PHONY : plotitem.cpp.i

plotitem.s: plotitem.cpp.s
.PHONY : plotitem.s

# target to generate assembly for a file
plotitem.cpp.s:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/plotitem.cpp.s
.PHONY : plotitem.cpp.s

point.o: point.cpp.o
.PHONY : point.o

# target to build an object file
point.cpp.o:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/point.cpp.o
.PHONY : point.cpp.o

point.i: point.cpp.i
.PHONY : point.i

# target to preprocess a source file
point.cpp.i:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/point.cpp.i
.PHONY : point.cpp.i

point.s: point.cpp.s
.PHONY : point.s

# target to generate assembly for a file
point.cpp.s:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/point.cpp.s
.PHONY : point.cpp.s

siporangeqtpart0.o: siporangeqtpart0.cpp.o
.PHONY : siporangeqtpart0.o

# target to build an object file
siporangeqtpart0.cpp.o:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/siporangeqtpart0.cpp.o
.PHONY : siporangeqtpart0.cpp.o

siporangeqtpart0.i: siporangeqtpart0.cpp.i
.PHONY : siporangeqtpart0.i

# target to preprocess a source file
siporangeqtpart0.cpp.i:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/siporangeqtpart0.cpp.i
.PHONY : siporangeqtpart0.cpp.i

siporangeqtpart0.s: siporangeqtpart0.cpp.s
.PHONY : siporangeqtpart0.s

# target to generate assembly for a file
siporangeqtpart0.cpp.s:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/siporangeqtpart0.cpp.s
.PHONY : siporangeqtpart0.cpp.s

unconnectedlinescurve.o: unconnectedlinescurve.cpp.o
.PHONY : unconnectedlinescurve.o

# target to build an object file
unconnectedlinescurve.cpp.o:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/unconnectedlinescurve.cpp.o
.PHONY : unconnectedlinescurve.cpp.o

unconnectedlinescurve.i: unconnectedlinescurve.cpp.i
.PHONY : unconnectedlinescurve.i

# target to preprocess a source file
unconnectedlinescurve.cpp.i:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/unconnectedlinescurve.cpp.i
.PHONY : unconnectedlinescurve.cpp.i

unconnectedlinescurve.s: unconnectedlinescurve.cpp.s
.PHONY : unconnectedlinescurve.s

# target to generate assembly for a file
unconnectedlinescurve.cpp.s:
	$(MAKE) -f CMakeFiles/python_module_orangeqt.dir/build.make CMakeFiles/python_module_orangeqt.dir/unconnectedlinescurve.cpp.s
.PHONY : unconnectedlinescurve.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... python_module_orangeqt"
	@echo "... rebuild_cache"
	@echo "... canvas3d.o"
	@echo "... canvas3d.i"
	@echo "... canvas3d.s"
	@echo "... curve.o"
	@echo "... curve.i"
	@echo "... curve.s"
	@echo "... glextensions.o"
	@echo "... glextensions.i"
	@echo "... glextensions.s"
	@echo "... multicurve.o"
	@echo "... multicurve.i"
	@echo "... multicurve.s"
	@echo "... networkcurve.o"
	@echo "... networkcurve.i"
	@echo "... networkcurve.s"
	@echo "... plot.o"
	@echo "... plot.i"
	@echo "... plot.s"
	@echo "... plot3d.o"
	@echo "... plot3d.i"
	@echo "... plot3d.s"
	@echo "... plotitem.o"
	@echo "... plotitem.i"
	@echo "... plotitem.s"
	@echo "... point.o"
	@echo "... point.i"
	@echo "... point.s"
	@echo "... siporangeqtpart0.o"
	@echo "... siporangeqtpart0.i"
	@echo "... siporangeqtpart0.s"
	@echo "... unconnectedlinescurve.o"
	@echo "... unconnectedlinescurve.i"
	@echo "... unconnectedlinescurve.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

